ALTER TABLE "PlanExercise" ADD COLUMN IF NOT EXISTS "groupId" TEXT;
ALTER TABLE "PlanExercise" ADD COLUMN IF NOT EXISTS "groupType" TEXT;
ALTER TABLE "PlanExercise" ADD COLUMN IF NOT EXISTS "dropSets" INTEGER NOT NULL DEFAULT 0;
